apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-analyzer-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: go-analyzer.local
      http:
        paths:
          - path: /ingest
            pathType: Prefix
            backend:
              service:
                name: go-analyzer
                port:
                  number: 80
          - path: /analyze
            pathType: Prefix
            backend:
              service:
                name: go-analyzer
                port:
                  number: 80
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: go-analyzer
                port:
                  number: 80
